### PR TITLE
feat: initial implementation

### PR DESCRIPTION
**Pull request by wemeetagain**
Implementation snatched from rust stdlib

between 30 and 300x faster than `isIP` from `is-ip`

### CODE REVIEW

**Review by dapplion — APPROVED** [review]
LGTM =D

**Comment by achingbrain** [comment]
Can this be benched against [net.isIP](https://nodejs.org/api/net.html#netisipinput) as well?  Can do a node/browser switch out in `package.json` for the node api if it's faster.

**Comment by wemeetagain** [comment]
It's there in the current benchmark.
Here's the result run on my laptop:
```
  isIPv4
    ✔ ours.isIPv4("0.0.0.0")                                              487092.1 ops/s    2.053000 us/op   x0.969     384097 runs  0.909 s
    ✔ ours.isIPv4("192.168.0.1")                                          480769.2 ops/s    2.080000 us/op   x0.967     300431 runs  0.707 s
    ✔ ours.isIPv4("255.255.255.255")                                      467071.5 ops/s    2.141000 us/op   x0.997     124482 runs  0.303 s
    ✔ ours.isIPv4("0.0f.0.0")                                             496524.3 ops/s    2.014000 us/op   x0.979     221674 runs  0.505 s
    ✔ ours.isIPv4("hahahahah")                                            654022.2 ops/s    1.529000 us/op   x1.006     565106 runs   1.01 s
    ✔ ours.isIPv4("999.0.0.0")                                            877193.0 ops/s    1.140000 us/op   x0.605     290316 runs  0.404 s
    ✔ ours.isIPv4("0000.0000.0000.0000")                                   2364066 ops/s    423.0000 ns/op   x1.014     448579 runs  0.303 s
    ✔ net.isIPv4("0.0.0.0")                                                3745318 ops/s    267.0000 ns/op   x0.921     988822 runs  0.505 s
    ✔ net.isIPv4("192.168.0.1")                                            3703704 ops/s    270.0000 ns/op   x0.928    1182834 runs  0.606 s
    ✔ net.isIPv4("255.255.255.255")                                        3484321 ops/s    287.0000 ns/op   x0.947     572983 runs  0.303 s
    ✔ net.isIPv4("0.0f.0.0")                                               3952569 ops/s    253.0000 ns/op   x0.927    1023410 runs  0.505 s
    ✔ net.isIPv4("hahahahah")                                              4132231 ops/s    242.0000 ns/op   x0.931    1252491 runs  0.606 s
    ✔ net.isIPv4("999.0.0.0")                                              4098361 ops/s    244.0000 ns/op   x0.928     835074 runs  0.404 s
    ✔ net.isIPv4("0000.0000.0000.0000")                                    4115226 ops/s    243.0000 ns/op   x0.927     841438 runs  0.404 s
    ✔ isIpLib.isIPv4("0.0.0.0")                                           1621.431 ops/s    616.7390 us/op   x0.989       1307 runs   1.31 s
    ✔ isIpLib.isIPv4("192.168.0.1")                                       1725.140 ops/s    579.6630 us/op   x0.949       2085 runs   1.71 s
    ✔ isIpLib.isIPv4("255.255.255.255")                                   1686.813 ops/s    592.8340 us/op   x0.999       1533 runs   1.41 s
    ✔ isIpLib.isIPv4("0.0f.0.0")                                          1787.796 ops/s    559.3480 us/op   x0.909        542 runs  0.806 s
    ✔ isIpLib.isIPv4("hahahahah")                                         1645.551 ops/s    607.6990 us/op   x0.983       2498 runs   2.02 s
    ✔ isIpLib.isIPv4("999.0.0.0")                                         1624.764 ops/s    615.4740 us/op   x0.995       1642 runs   1.51 s
    ✔ isIpLib.isIPv4("0000.0000.0000.0000")                               1595.337 ops/s    626.8270 us/op   x1.039       1769 runs   1.61 s

  isIPv6
    ✔ ours.isIPv6("1:2:3:4:5:6:7:8")                                      49438.87 ops/s    20.22700 us/op   x0.999      47206 runs   1.01 s
    ✔ ours.isIPv6("::1")                                                  111259.5 ops/s    8.988000 us/op   x1.088      30636 runs  0.303 s
    ✔ ours.isIPv6("0000:0000:0000:0000:0000:0000:0000:0000")              49880.29 ops/s    20.04800 us/op   x0.945      33623 runs  0.707 s
    ✔ ours.isIPv6("0000:0000:0000:0000:0000:ffff:192.168.100.228")        66800.27 ops/s    14.97000 us/op   x0.952      51425 runs  0.808 s
    ✔ ours.isIPv6("2001:0dc5:72a3:0000:0000:802e:3370:73E4")              58058.52 ops/s    17.22400 us/op   x0.955      27803 runs  0.505 s
    ✔ ours.isIPv6("hahahahahahaha")                                       241138.2 ops/s    4.147000 us/op        -     159521 runs  0.707 s
    ✔ ours.isIPv6("0000.0000:0000.0000")                                  221582.1 ops/s    4.513000 us/op        -     189617 runs  0.909 s
    ✔ net.isIPv6("1:2:3:4:5:6:7:8")                                        2659574 ops/s    376.0000 ns/op   x0.974    1457790 runs  0.909 s
    ✔ net.isIPv6("::1")                                                    2659574 ops/s    376.0000 ns/op   x0.913     972710 runs  0.606 s
    ✔ net.isIPv6("0000:0000:0000:0000:0000:0000:0000:0000")                2610966 ops/s    383.0000 ns/op   x0.857    1283693 runs  0.809 s
    ✔ net.isIPv6("0000:0000:0000:0000:0000:ffff:192.168.100.228")          1930502 ops/s    518.0000 ns/op   x0.893     921839 runs  0.707 s
    ✔ net.isIPv6("2001:0dc5:72a3:0000:0000:802e:3370:73E4")                2590674 ops/s    386.0000 ns/op   x0.879     957315 runs  0.606 s
    ✔ net.isIPv6("hahahahahahaha")                                         3076923 ops/s    325.0000 ns/op        -     704505 runs  0.404 s
    ✔ net.isIPv6("0000.0000:0000.0000")                                    2475248 ops/s    404.0000 ns/op        -     761644 runs  0.505 s
    ✔ isIpLib.isIPv6("1:2:3:4:5:6:7:8")                                   1598.951 ops/s    625.4100 us/op   x0.925       1941 runs   1.72 s
    ✔ isIpLib.isIPv6("::1")                                               1567.361 ops/s    638.0150 us/op   x0.958       1898 runs   1.72 s
    ✔ isIpLib.isIPv6("0000:0000:0000:0000:0000:0000:0000:0000")           1642.746 ops/s    608.7370 us/op   x0.901       1494 runs   1.41 s
    ✔ isIpLib.isIPv6("0000:0000:0000:0000:0000:ffff:192.168.100.228")     1653.641 ops/s    604.7260 us/op   x0.882       3008 runs   2.33 s
    ✔ isIpLib.isIPv6("2001:0dc5:72a3:0000:0000:802e:3370:73E4")           1566.382 ops/s    638.4140 us/op   x0.972       1107 runs   1.21 s
    ✔ isIpLib.isIPv6("hahahahahahaha")                                    1613.314 ops/s    619.8420 us/op        -       1951 runs   1.71 s
    ✔ isIpLib.isIPv6("0000.0000:0000.0000")                               1686.884 ops/s    592.8090 us/op        -       2557 runs   2.02 s

  isIP
    ✔ ours.isIP("0.0.0.0")                                                464900.0 ops/s    2.151000 us/op        -     420534 runs   1.01 s
    ✔ ours.isIP("192.168.0.1")                                            457875.5 ops/s    2.184000 us/op        -     165566 runs  0.404 s
    ✔ ours.isIP("255.255.255.255")                                        450045.0 ops/s    2.222000 us/op        -     285827 runs  0.707 s
    ✔ ours.isIP("0.0f.0.0")                                               140213.1 ops/s    7.132000 us/op        -     162464 runs   1.21 s
    ✔ ours.isIP("hahahahah")                                              172592.3 ops/s    5.794000 us/op        -      48952 runs  0.303 s
    ✔ ours.isIP("999.0.0.0")                                              180570.6 ops/s    5.538000 us/op        -      68696 runs  0.404 s
    ✔ ours.isIP("0000.0000.0000.0000")                                    179372.2 ops/s    5.575000 us/op        -      68001 runs  0.404 s
    ✔ ours.isIP("1:2:3:4:5:6:7:8")                                        50246.21 ops/s    19.90200 us/op        -      34006 runs  0.707 s
    ✔ ours.isIP("::1")                                                    106849.0 ops/s    9.359000 us/op        -      40274 runs  0.404 s
    ✔ ours.isIP("0000:0000:0000:0000:0000:0000:0000:0000")                54522.65 ops/s    18.34100 us/op        -      26091 runs  0.505 s
    ✔ ours.isIP("0000:0000:0000:0000:0000:ffff:192.168.100.228")          59417.71 ops/s    16.83000 us/op        -      22653 runs  0.404 s
    ✔ ours.isIP("2001:0dc5:72a3:0000:0000:802e:3370:73E4")                50097.69 ops/s    19.96100 us/op        -      78786 runs   1.62 s
    ✔ ours.isIP("hahahahahahaha")                                         180603.2 ops/s    5.537000 us/op        -     138441 runs  0.808 s
    ✔ ours.isIP("0000.0000:0000.0000")                                    184297.8 ops/s    5.426000 us/op        -     104967 runs  0.606 s
    ✔ net.isIP("0.0.0.0")                                                  3546099 ops/s    282.0000 ns/op        -    1176836 runs  0.606 s
    ✔ net.isIP("192.168.0.1")                                              3484321 ops/s    287.0000 ns/op        -     580345 runs  0.303 s
    ✔ net.isIP("255.255.255.255")                                          3344482 ops/s    299.0000 ns/op        -    1148451 runs  0.606 s
    ✔ net.isIP("0.0f.0.0")                                                 2433090 ops/s    411.0000 ns/op        -    2855786 runs   1.92 s
    ✔ net.isIP("hahahahah")                                                2865330 ops/s    349.0000 ns/op        -    1520122 runs  0.909 s
    ✔ net.isIP("999.0.0.0")                                                2347418 ops/s    426.0000 ns/op        -     591465 runs  0.404 s
    ✔ net.isIP("0000.0000.0000.0000")                                      2293578 ops/s    436.0000 ns/op        -     874343 runs  0.606 s
    ✔ net.isIP("1:2:3:4:5:6:7:8")                                          2450980 ops/s    408.0000 ns/op        -     767750 runs  0.505 s
    ✔ net.isIP("::1")                                                      2469136 ops/s    405.0000 ns/op        -     770679 runs  0.505 s
    ✔ net.isIP("0000:0000:0000:0000:0000:0000:0000:0000")                  2439024 ops/s    410.0000 ns/op        -     610123 runs  0.404 s
    ✔ net.isIP("0000:0000:0000:0000:0000:ffff:192.168.100.228")            1828154 ops/s    547.0000 ns/op        -     503245 runs  0.404 s
    ✔ net.isIP("2001:0dc5:72a3:0000:0000:802e:3370:73E4")                  2336449 ops/s    428.0000 ns/op        -    1489379 runs   1.01 s
    ✔ net.isIP("hahahahahahaha")                                           2923977 ops/s    342.0000 ns/op        -     684765 runs  0.404 s
    ✔ net.isIP("0000.0000:0000.0000")                                      2309469 ops/s    433.0000 ns/op        -     590156 runs  0.404 s
    ✔ isIpLib.isIP("0.0.0.0")                                             1610.942 ops/s    620.7550 us/op        -       2609 runs   2.13 s
    ✔ isIpLib.isIP("192.168.0.1")                                         1681.178 ops/s    594.8210 us/op        -       1864 runs   1.61 s
    ✔ isIpLib.isIP("255.255.255.255")                                     1694.841 ops/s    590.0260 us/op        -        342 runs  0.704 s
    ✔ isIpLib.isIP("0.0f.0.0")                                            1596.985 ops/s    626.1800 us/op        -       2258 runs   1.92 s
    ✔ isIpLib.isIP("hahahahah")                                           1598.777 ops/s    625.4780 us/op        -       2590 runs   2.13 s
    ✔ isIpLib.isIP("999.0.0.0")                                           1382.596 ops/s    723.2770 us/op        -       1403 runs   1.52 s
    ✔ isIpLib.isIP("0000.0000.0000.0000")                                 1528.769 ops/s    654.1210 us/op        -       4472 runs   3.44 s
    ✔ isIpLib.isIP("1:2:3:4:5:6:7:8")                                     1600.853 ops/s    624.6670 us/op        -       2743 runs   2.22 s
    ✔ isIpLib.isIP("::1")                                                 1514.789 ops/s    660.1580 us/op        -       1069 runs   1.21 s
    ✔ isIpLib.isIP("0000:0000:0000:0000:0000:0000:0000:0000")             1571.934 ops/s    636.1590 us/op        -       1901 runs   1.71 s
    ✔ isIpLib.isIP("0000:0000:0000:0000:0000:ffff:192.168.100.228")       1547.961 ops/s    646.0110 us/op        -       1885 runs   1.72 s
    ✔ isIpLib.isIP("2001:0dc5:72a3:0000:0000:802e:3370:73E4")             1577.449 ops/s    633.9350 us/op        -       2754 runs   2.25 s
    ✔ isIpLib.isIP("hahahahahahaha")                                      1618.807 ops/s    617.7390 us/op        -       1807 runs   1.62 s
    ✔ isIpLib.isIP("0000.0000:0000.0000")                                 1456.352 ops/s    686.6470 us/op        -       2062 runs   1.92 s
```

**Comment by wemeetagain** [comment]
> Can do a node/browser switch out in package.json for the node api if it's faster.

Yea good idea. It's roughly 6x faster for `isIPv4` and 60x faster for `isIPv6`

**Pull request merged**
